name: Trigon420
description: Trigon WebGL/software rendering thing for easy pixel rendering
version: 0.0.1
environment:
  sdk: '>=1.0.0 <2.0.0'
#dependencies:
#  lib_name: any
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
